# Generated by Django 3.2.3 on 2021-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField(null=True)),
                ('Department', models.CharField(choices=[('Computer Lab', 'Computer Lab'), ('Physics Lab', 'Physics Lab'), ('Account', 'Account'), ('Bus', 'Bus'), ('Library', 'Library'), ('School/Dept Administration', 'School/Dept Administration'), ('Student Welfare', 'Student Welfare')], max_length=200, null=True)),
                ('Clear', models.CharField(choices=[('All Clear', 'All Clear'), ('Semi Clear', 'Semi Clear')], max_length=200, null=True)),
                ('DateCleared', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('ClearedBy', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'unique_together': {('student', 'Department', 'name')},
            },
        ),
    ]
