# Generated by Django 3.2.3 on 2021-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_alter_updateinfo_clearedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='AmountLeft',
            field=models.IntegerField(null=True),
        ),
    ]
