# Generated by Django 3.2.3 on 2021-05-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=200, null=True)),
                ('Clear', models.CharField(choices=[('All Clear', 'All Clear'), ('Semi Clear', 'Semi Clear')], max_length=200, null=True)),
                ('DateCleared', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
            ],
        ),
    ]
