# Generated by Django 3.2.3 on 2021-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clearance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='student',
            field=models.IntegerField(null=True),
        ),
    ]
