# Generated by Django 3.2.3 on 2021-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clearance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clearance',
            unique_together={('student', 'Department', 'name')},
        ),
    ]
