# Generated by Django 3.2.3 on 2021-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210525_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='ClearedBy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='DateCleared',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
