# Generated by Django 3.2.3 on 2021-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clearance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='DateCleared',
            field=models.DateTimeField(null=True),
        ),
    ]
