# Generated by Django 3.2.3 on 2021-06-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updateInfo',
        ),
    ]
