# Generated by Django 3.2.3 on 2021-06-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('update', '0007_updateinfo_amountleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='ClearedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
