# Generated by Django 3.2.3 on 2021-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='Department',
            field=models.CharField(choices=[('Computer Lab', 'Computer Lab'), ('Physics Lab', 'Physics Lab'), ('Account', 'Account'), ('Bus', 'Bus'), ('Library', 'Library'), ('School/Dept Administration', 'School/Dept Administration'), ('Student Welfare', 'Student Welfare')], max_length=200, null=True),
        ),
    ]
