# Generated by Django 3.2.3 on 2021-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210527_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='DateCleared',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
