# Generated by Django 3.2.3 on 2021-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_clearance_datecleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
