# Generated by Django 3.2.3 on 2021-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_clearance_clearedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
