# Generated by Django 3.2.3 on 2021-06-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_alter_clearance_clearedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='AmountLeft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='ClearedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
